### PR TITLE
Add Child Rows

### PR DESCRIPTION
**Pull request by RossKen**
Adding child rows and implementing other design changes
- change date formats
- add more graph interactivity

### CODE REVIEW

**Comment by EdwardAndress** [comment]
Hi @RossKen - brace yourself!

Some initial comments on process...

It would be helpful to have a bit more detail in the comments at the start of a PR.  I wasn't really sure, for example, what you meant by 'child rows'.  Also, commit messages should describe why changes were made (within 50 chars) so that we can look back at the log and understand something about what went on.  Finally, each commit that goes into master should build successfully.  If not, we can't revert to previous commits with any confidence that the app will still work.

Some comments on the code...

I've run this locally and it all seems fine but it would be better to make the whole row clickable - do you know how to do that?  Of course there could also be a test or two here ;)

**Comment by RossKen** [comment]
@EdwardAndress You are right, this could have been clearer. When I found this functionality in DT the were called child rows so just stuck with that - obviously this is not immediately intuative and should be changed.

As for the functionality, I am not sure about clicking the whole row for this - the child rows part is done by imbedding some javascript which I do not fully understand - but I will investigate. 

Am spending all of tomorrow on this so will also get some tests up and running.

**Comment by EdwardAndress** [comment]
@RossKen - thanks for humouring me.  I can try to help with the JS.  I'll do some investigating today and send over anything I find useful.

**Comment by EdwardAndress** [comment]
@RossKen - I don't know why the tests are not running properly

**Comment by RossKen** [comment]
hmm... not ideal

**Comment by EdwardAndress** [comment]
I will try to fix it

**Pull request merged**
