### PR TITLE
Implement UX Feedback

### PR DESCRIPTION
**Pull request by RossKen**

### CODE REVIEW

**Comment by RossKen** [comment]
@EdwardAndress Following the UX meeting we had earlier in the week there is an option to choose how many similar qs you want returned. This throws off some of the travis tests you put in place so probably worth having a chat about how we can change these going forward.

**Comment by EdwardAndress** [comment]
@RossKen - The changes you made have effected the function of the app, rather than broken it, so you can justifiably change the expectations in the tests (on lines 23, 24, and 25 of test-search.R)

The simplest fix would be to change the expected number of odd and even rows to 5 and the expected number of total rows to 10 (because, by default, 10 questions are returned).  This is fine and is as good as the original test.

The goal of the test, however, is to prove that search functionality works.  Perhaps you can think of a better way to test this.  If so, I can help you to implement it.  If you do, you could add another test for the radio buttons.  This could be done by recycling a lot of the search test but adding in a extra step where the radio buttons are used and the expectations are set accordingly.

**Comment by EdwardAndress** [comment]
You could also add a test for the date range! ;)

**Comment by RossKen** [comment]
Have implemented your suggestion as a quick fix, but will have a think about how to possibly rework/extend the testing in the longer term

**Comment by EdwardAndress** [comment]
Nice work dude!

**Comment by EdwardAndress** [comment]
@RossKen - if you have time, we could write some simple tests for the radio buttons together and include it in this PR.

**Comment by RossKen** [comment]
@EdwardAndress test has been added. Sorry for the delay, it was hiding in a random corner of my local machine

**Comment by EdwardAndress** [comment]
I see there's a failing test with an unhelpful error message - do you want some help?

**Comment by RossKen** [comment]
I think I know what it is, so I will have a look - but I reserve the right to ask for help in the event that I fail miserably

**Pull request merged**
